name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18', '1.19' ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        check-latest: true
    - run: make build
    - run: make test
    - uses: dominikh/staticcheck-action@v1.3.1
      with:
        version: "2023.1.7"
        install-go: false
